# File: .streamlit/config.toml

[theme]
# Màu chính cho các widget tương tác (nút bấm, slider...)
primaryColor="#4CAF50"

# Màu nền chính của ứng dụng
backgroundColor="#f0fff3ff"

# Màu nền phụ (cho sidebar, expander...)
secondaryBackgroundColor="#bcd8c1ff"

# Màu chữ chính
textColor="#000000ff"

# Font chữ (có thể là 'sans serif', 'serif', hoặc 'monospace')
font="sans serif"